import { Injectable, Logger } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { LlmService } from '../llm/llm.service'
import { CHATBOT_PROMPT_TEMPLATES } from '../common/prompts/chatbot.prompts'
import { SessionEntity } from 'src/core/models'

/**
 * ChatbotService
 *
 * Main orchestrator for chatbot interactions.
 * Handles message flow, language detection, prompt building, and LLM interaction.
 * Chat memory and RAG are handled internally by LlmService via LangChain Memory and tools.
 */
@Injectable()
export class ChatbotService {
  private readonly logger = new Logger(ChatbotService.name)

  /**
   * Constructs the ChatbotService with required dependencies.
   * @param llmService LLM interaction service (model agnostic).
   * @param configService NestJS config service (speaker tag settings).
   */
  constructor(
    private readonly llmService: LlmService,
    private readonly configService: ConfigService,
  ) {}

  /**
   * Build a speaker tag prefix for multiplayer workspaces so the LLM can
   * disambiguate who is speaking despite a shared memory. Returns an empty
   * string in non-workspace mode or when speaker tags are disabled.
   */
  private buildSpeakerTag(session: SessionEntity): string {
    if (!session.activeWorkspaceId) return ''
    const enabled = this.configService.get<boolean>('appConfig.holoclaw.speakerTags.enabled') ?? true
    if (!enabled) return ''
    const format =
      this.configService.get<string>('appConfig.holoclaw.speakerTags.format') ?? '[{identity}:{role}]: '
    const identity = session.userIdentity || session.userName || 'guest'
    const role = session.userRoles?.[0] || 'member'
    return format.replace('{identity}', identity).replace('{role}', role)
  }

  /**
   * Handles a new user chat input.
   *  - Detects input language (if not provided)
   *  - Builds the LLM prompt in the appropriate language
   *  - Calls the LLM provider (which manages memory and RAG internally)
   *
   * @param options Options object containing userInput and session.
   * @returns The agent's reply as generated by the LLM.
   */
  async chat(options: { userInput: string; session: SessionEntity; isAdmin?: boolean }): Promise<string> {
    const { userInput, session, isAdmin } = options
    const { lang, connectionId, userName } = session

    this.logger.debug(`Received user input: "${userInput}" [connectionId: ${connectionId}]`)

    // Detect language of user input (or fallback to session lang)
    let userLang = await this.llmService.detectLanguage(userInput)

    if (!userLang && lang) {
      userLang = lang
      this.logger.log(`Detected user language: ${userLang}`)
    } else {
      this.logger.log(`Using detected user language: ${userLang}`)
    }

    // HoloClaw: in workspace mode, prepend a speaker tag so the LLM can
    // disambiguate who is speaking over the shared workspace memory.
    const speakerTag = this.buildSpeakerTag(session)
    const taggedInput = speakerTag ? `${speakerTag}${userInput}` : userInput

    // Build prompt using language-appropriate template.
    const template = CHATBOT_PROMPT_TEMPLATES[userLang] || CHATBOT_PROMPT_TEMPLATES['en']
    const prompt = template('', taggedInput, userName)
    this.logger.verbose(`Final prompt built for LLM:\n${prompt}`)

    // Call LLM to get response (memory + RAG via tools se manejan dentro de LlmService)
    const answer = await this.llmService.generate(prompt, { session, isAdmin })
    this.logger.debug(`LLM generated answer: "${answer}"`)

    this.logger.log(`Chat handled via LlmService (memory + RAG tools) for session: ${connectionId}`)

    return answer
  }
}
